#!/usr/bin/env bash
set -euo pipefail

PACKAGES=(cmake git libraspberrypi-dev xserver-xorg-input-evdev)
apt install -y "${PACKAGES[@]}"

# Install DeviceTree's
cp bin/tft35a-overlay.dtb /boot/firmware/overlays/tft35a.dtbo

# Firmware config
tee -a /boot/firmware/config.txt <<EOF
hdmi_force_hotplug=1
dtparam=i2c_arm=on
dtparam=spi=on
enable_uart=1
dtoverlay=tft35a:rotate=__PLACEHOLDER__
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_cvt=__PLACEHOLDER__
hdmi_drive=2
EOF

if grep vc4-kms-v3d /boot/firmware/config.txt; then
    echo 'WARNING: Make sure to disable vc4-kms-v3d overlay in /boot/firmware/config.txt'
fi

# Framebuffer copy daemon
git clone https://github.com/tasanakorn/rpi-fbcp rpi-fbcp
mkdir rpi-fbcp/build
cmake -B rpi-fbcp/build rpi-fbcp
make -C rpi-fbcp/build
install rpi-fbcp/build/fbcp /usr/local/bin/fbcp
tee /etc/systemd/system/fbcp.service <<EOF
[Unit]
Description=fbcp

[Service]
ExecStartPre=/usr/bin/sleep 7
ExecStart=/usr/local/bin/fbcp

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable fbcp.service
