#!/usr/bin/env bash

rm -rf /etc/X11/xorg.conf.d/40-libinput.conf

cp ./usr/tft35a-overlay.dtb /boot/firmware/overlays/
cp ./usr/tft35a-overlay.dtb /boot/firmware/overlays/tft35a.dtbo

tee -a /boot/firmware/config.txt <<EOF
hdmi_force_hotplug=1
dtparam=i2c_arm=on
dtparam=spi=on
enable_uart=1
dtoverlay=tft35a:rotate=90
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_cvt 480 320 60 6 0 0 0
hdmi_drive=2
EOF

tee /etc/X11/xorg.conf.d/99-calibration.conf <<EOF
Section "InputClass"
        Identifier      "calibration"
        MatchProduct    "ADS7846 Touchscreen"
        Option  "Calibration"   "3936 227 268 3880"
        Option  "SwapAxes"      "1"
EndSection
EOF

cp ./usr/inittab /etc/

apt install -y cmake libraspberrypi-dev
git clone https://github.com/tasanakorn/rpi-fbcp rpi-fbcp
mkdir rpi-fbcp/build
cmake -B rpi-fbcp/build rpi-fbcp
make -C rpi-fbcp/build
install rpi-fbcp/build/fbcp /usr/local/bin/fbcp
cp -rf ./etc/rc.local /etc/rc.local

apt install -y xserver-xorg-input-evdev
cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf
